export enum CountryEnum {
  EGYPT = 'Egypt',
  SAUDI_ARABIA = 'Saudi Arabia',
  UAE = 'UAE',
  KUWAIT = 'Kuwait',
  QATAR = 'Qatar',
  BAHRAIN = 'Bahrain',
  OMAN = 'Oman',
  JORDAN = 'Jordan',
  PALESTINE = 'Palestine',
  LEBANON = 'Lebanon',
  SYRIA = 'Syria',
  IRAQ = 'Iraq',
  YEMEN = 'Yemen',
  LIBYA = 'Libya',
  TUNISIA = 'Tunisia',
  ALGERIA = 'Algeria',
  MOROCCO = 'Morocco',
  SUDAN = 'Sudan',
  MAURITANIA = 'Mauritania',
  SOMALIA = 'Somalia',
  DJIBOUTI = 'Djibouti',
  COMOROS = 'Comoros',
}
